### ISSUE TITLE
AWS CloudWatch

### ISSUE THREAD

**Issue by cutegyuseok** [Final-Project-Team6/BE_Project#13]
## Title
AWS CloudWatch logs 적용

## Description
spring에서의 로깅 먼저 활성화 후 AWS CloudWatch logs 적용

## References

- [AWS DOC](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html)

**Comment by cutegyuseok** [comment]
로깅 관련해서 의견 있으시면 자유롭게 남겨주세요!

**Comment by LimdaeIl** [comment]
저는 지금 괜찮습니다 :)
